### ISSUE TITLE
blastdb download 

### ISSUE THREAD

**Issue by aiqubo** [biologger/speciesprimer#1]
"root@c5299f64bf4d:/blastdb# getblastdb.py -db ref_prok_rep_genomes -dbpath /blastdb --delete

Start Download of NCBI ref_prok_rep_genomes BLAST database

> Downloading...ref_prok_rep_genomes.00.tar.gz
  0% [                                                                      ]    901120 / 994107480Traceback (most recent call last):
  File "/pipeline/getblastdb.py", line 368, in <module>
    get_DB()
  File "/pipeline/getblastdb.py", line 358, in get_DB
    download_from_ftp(filelist, conf)
  File "/pipeline/getblastdb.py", line 217, in download_from_ftp
    filename, conf)
  File "/pipeline/getblastdb.py", line 198, in handle_md5_archive
    wget_download(filename, conf)
  File "/pipeline/getblastdb.py", line 99, in wget_download
    wget.download(url, archivename)
  File "/usr/local/lib/python3.5/dist-packages/wget.py", line 526, in download
    (tmpfile, headers) = ulib.urlretrieve(binurl, tmpfile, callback)
  File "/usr/lib/python3.5/urllib/request.py", line 229, in urlretrieve
    % (read, size), result)
urllib.error.ContentTooShortError: <urlopen error retrieval incomplete: got only 899208 out of 994107480 bytes>"
Thank you for your great program, I use speciesprimer in centOS docker with Command-line,but it seems that there is an error when download blastdb,Is it something wrong?

**Comment by biologger** [comment]
Hi,
I was not able to reproduce this error using the SpeciesPrimer Docker images v2.1.2 and latest.
The issue may be related to a unstable internet connection. 
Did you try to restart the script after some time?

Alternative download options are:
manually 
[https://ftp.ncbi.nlm.nih.gov/blast/db/](https://ftp.ncbi.nlm.nih.gov/blast/db/)
BLAST+ script
`update_blastdb.pl --passive --decompress ref_prok_rep_genomes`

**Comment by aiqubo** [comment]
Thank you very much
I solved the problem about  blastdb according to your suggestion
Another problem occurred while running the speciesprimer.py with default parameters
"Start searching primer for Legionella_pneumophila
fatal error while working on Legionella_pneumophila check logfile /primerdesign/speciesprimer_2020_02_26.log
IncompleteRead(246 bytes read)
Traceback (most recent call last):
  File "/usr/lib/python3.5/http/client.py", line 593, in _readinto_chunked
    n = self._safe_readinto(temp_mvb)
  File "/usr/lib/python3.5/http/client.py", line 635, in _safe_readinto
    raise IncompleteRead(bytes(mvb[0:total_bytes]), len(b))
http.client.IncompleteRead: IncompleteRead(0 bytes read, 3425 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pipeline/speciesprimer.py", line 4165, in main
    run_pipeline_for_target(target, config)
  File "/pipeline/speciesprimer.py", line 4051, in run_pipeline_for_target
    newconfig = DataCollection(config).collect()
  File "/pipeline/speciesprimer.py", line 647, in collect
    self.get_ncbi_links(taxid)
  File "/pipeline/speciesprimer.py", line 276, in get_ncbi_links
    genomedata = collect_genomedata(taxid, email)
  File "/pipeline/speciesprimer.py", line 223, in collect_genomedata
    assembly_records = Entrez.read(assembly_efetch)
  File "/usr/local/lib/python3.5/dist-packages/Bio/Entrez/__init__.py", line 478, in read
    record = handler.read(handle)
  File "/usr/local/lib/python3.5/dist-packages/Bio/Entrez/Parser.py", line 334, in read
    self.parser.ParseFile(handle)
  File "/usr/lib/python3.5/http/client.py", line 488, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.5/http/client.py", line 599, in _readinto_chunked
    raise IncompleteRead(bytes(b[0:total_bytes]))
http.client.IncompleteRead: IncompleteRead(246 bytes read)
Error report:
for target Legionella_pneumophila
Error 1:
fatal error while working on Legionella_pneumophila check logfile /primerdesign/speciesprimer_2020_02_26.log"

**Comment by biologger** [comment]
I was not able to reproduce this behavior, again the issue seems related to an unstable internet connection. This time affecting the Biopython Entrez Module during the collection of the genome assembly FTP links from the NCBI Entrez Server.

A possible workaround would be to use a download tool that tries to reconnect and download the files several times.

I would try to download the genome assemblies with [https://github.com/kblin/ncbi-genome-download](https://github.com/kblin/ncbi-genome-download) and subsequently run speciesprimer in offline mode.

In the docker container terminal run:
```
pip3 install ncbi-genome-download
cd /primerdesign
ncbi-genome-download --genus "Legionella pneumophila" --format fasta --assembly-level complete,chromosome bacteria
cd refseq/bacteria
gunzip -r *
cp **/*.fna /primerdesign/Legionella_pneumophila/genomic_fna
speciesprimer.py -t Legionella_pneumophila --customdb ref_prok_rep_genomes --offline
```

**Comment by aiqubo** [comment]
Thank you for your advice and help

I will try as you suggested
