### ISSUE TITLE
md5 checksum failure

### ISSUE THREAD

**Issue by noah472** [biologger/speciesprimer#22]
Hi, 

I am trying to download the blast_db and keep getting the following md5 error using both the html and from the command line. Any ideas please?

thanks

Downloading...nt.00.tar.gz
100% [....................................................................] 4475995937 / 4475995937
md5Checksum nt.00.tar.gz

Error MD5 checksum not correct

File: ac641a037088694704c0adc0790490ba

Expected: c0d3f5f09610b5e2e4cdea380ffa381c

Problem with nt.00.tar.gz.md5. Please run getblastdb again to check if files are missing
Traceback (most recent call last):
  File "/pipeline/getblastdb.py", line 368, in <module>
    get_DB()
  File "/pipeline/getblastdb.py", line 358, in get_DB
    download_from_ftp(filelist, conf)
  File "/pipeline/getblastdb.py", line 217, in download_from_ftp
    filename, conf)
  File "/pipeline/getblastdb.py", line 198, in handle_md5_archive
    wget_download(filename, conf)
  File "/pipeline/getblastdb.py", line 101, in wget_download
    dbfile = check_md5(filename)
  File "/pipeline/getblastdb.py", line 129, in check_md5
    raise Exception
Exception

**Comment by biologger** [comment]
Hi,

At the moment I don't know what the problem is. 
As an alternative use the NCBI update_blastdb.pl script

```
  $ cd /blastdb

  $ update_blastdb.pl --passive --decompress nt
  # or
  $ update_blastdb.pl --passive --decompress ref_prok_rep_genomes
```

**Comment by noah472** [comment]
Hi,

thats great- seemed to be a problem with the same nt.00.tar.gz file again, took a few times to actually download and install.

thanks!

**Comment by noah472** [comment]
Just for info, I used the new version of the getblastdb.py and it kept failing, however, if the script is re-run when it fails then it starts the downloads again. The database is now working fine. Thanks
