### ISSUE TITLE
No BLAST DB was found

### ISSUE THREAD

**Issue by dominik1106** [biologger/speciesprimer#23]
Hello,

when I try to start a new run, I get the following error in my docker logs:
`
Traceback (most recent call last):
  File "/pipeline/gui/daemon/daemonize.py", line 75, in <module>
    main_daemon()
  File "/pipeline/gui/daemon/daemonize.py", line 56, in main_daemon
    d.start()
  File "/usr/local/lib/python3.5/dist-packages/mydaemon/__init__.py", line 107, in start
    self.run()
  File "/pipeline/gui/daemon/daemonclass.py", line 17, in run
    self.command()
  File "/pipeline/gui/daemon/daemonclass.py", line 50, in command
    speciesprimer.main(mode="auto")
  File "/pipeline/speciesprimer.py", line 4164, in main
    H.BLASTDB_check(config)
  File "/pipeline/basicfunctions.py", line 482, in BLASTDB_check
    raise BlastDBError(msg)
basicfunctions.BlastDBError: No BLAST DB was found nt_v5
`

The DB was downloaded via the WebInterface and I checked that it correctly shows up inside the container und /blastdb, looking with docker exec

**Comment by biologger** [comment]
Hi,

The pipeline is now a few years old, since then NCBI changed the default database version from 4 to 5.
Formerly the version 5 had a different name "nt_v5", now it is just "nt".

`basicfunctions.BlastDBError: No BLAST DB was found nt_v5`

That is why you don't need to set the blastdb5 option anymore even if you are using version5.
Please try to run the pipeline without the blastdb5 option, the database should then be found.
