### ISSUE TITLE
OSError: [Errno 30] Read-only file system: '/pipeline/tmp_config.json'

### ISSUE THREAD

**Issue by c-berruto** [biologger/speciesprimer#29]
Start searching primer for Bacillus_subtilis
To make use of NCBI's E-utilities, Please enter your email address. 
fatal error while working on Bacillus_subtilis check logfile /home/cberruto/speciesprimer_2024_07_29.log
[Errno 30] Read-only file system: '/pipeline/tmp_config.json'
Traceback (most recent call last):
  File "/pipeline/speciesprimer.py", line 4168, in main
    run_pipeline_for_target(target, config)
  File "/pipeline/speciesprimer.py", line 4054, in run_pipeline_for_target
    newconfig = DataCollection(config).collect()
  File "/pipeline/speciesprimer.py", line 645, in collect
    syn, taxid = self.get_taxid(self.target)
  File "/pipeline/speciesprimer.py", line 172, in get_taxid
    Entrez.email = H.get_email_for_Entrez()
  File "/pipeline/basicfunctions.py", line 461, in get_email_for_Entrez
    email = user_input_email(email)
  File "/pipeline/basicfunctions.py", line 451, in user_input_email
    with open(tmp_db_path, 'w') as f:
OSError: [Errno 30] Read-only file system: '/pipeline/tmp_config.json'
Error report: 
for target Bacillus_subtilis
Error 1:
fatal error while working on Bacillus_subtilis check logfile /home/cberruto/speciesprimer_2024_07_29.log

Any insight on how to fix this?

**Comment by biologger** [comment]
Hi,

It looks like you are not using docker for the run, are you running the pipeline locally or on singularity?

For singularity the problem there is that even it can run the docker image the container is read-only and in the current version of speciesprimer tries to write a temporary config file into the container.

Using docker or podman should work with the current version...

Alternativley, adding a CLI option for allowing a custom path for the tmp file for the config in the /primerdesign directory would probably fix this issue for singularity.

**Comment by wzacs1** [comment]
> Alternativley, adding a CLI option for allowing a custom path for the tmp file for the config in the /primerdesign directory would probably fix this issue for singularity.

This would be amazing! I am running through Singularity now and ended here.
