### ISSUE TITLE
ValueError: Your XML file was empty

### ISSUE THREAD

**Issue by aiqubo** [biologger/speciesprimer#3]
Could you help me about tihs error? Thank you very much!
“”“
27 Apr 2020 05:44:26: Run blastn -task megablast -num_threads 8 -query rRNA.part-0 -max_target_seqs 5 -max_hsps 1 -out rRNA_0_results.xml -outfmt 5 -db ref_prok_rep_genomes
27 Apr 2020 05:44:27: > Blast duration: 0:00:00
27 Apr 2020 05:44:27: Run: qc_blast_parser(rRNA)
27 Apr 2020 05:44:27: Run: blastresults_files(Bifidobacterium_animalis)
27 Apr 2020 05:44:27: > A problem with the BLAST results file /primerdesign/Bifidobacterium_animalis/rRNA_QC/rRNA_0_results.xml was detected. Please check if the file was removed and start$
27 Apr 2020 05:44:27: ['fatal error while working on', 'Bifidobacterium_animalis', 'check logfile', '/primerdesign/speciesprimer_2020_04_27.log']
fatal error while working on Bifidobacterium_animalis
Traceback (most recent call last):
  File "/pipeline//speciesprimer.py", line 4165, in main
    run_pipeline_for_target(target, config)
  File "/pipeline//speciesprimer.py", line 4056, in run_pipeline_for_target
    qc = QualityControl(config).quality_control(qc_gene)
  File "/pipeline//speciesprimer.py", line 1245, in quality_control
    passed_list = self.qc_blast_parser(qc_gene)
  File "/pipeline//speciesprimer.py", line 1060, in qc_blast_parser
    parse_blastresults()
  File "/pipeline//speciesprimer.py", line 974, in parse_blastresults
    blast_record_list = blapa.parse_BLASTfile(filename)
  File "/pipeline//speciesprimer.py", line 2152, in parse_BLASTfile
    record_list = list(blast_records)
  File "/usr/local/lib/python3.5/dist-packages/Bio/Blast/NCBIXML.py", line 798, in parse
    raise ValueError("Your XML file was empty")
ValueError: Your XML file was empty
27 Apr 2020 05:44:27: > Error report:
27 Apr 2020 05:44:27: > for target Bifidobacterium_animalis
27 Apr 2020 05:44:27: > Error 1:
27 Apr 2020 05:44:27: > A problem with the BLAST results file /primerdesign/Bifidobacterium_animalis/rRNA_QC/rRNA_0_results.xml was detected. Please check if the file was removed and start$
27 Apr 2020 05:44:27: > for target Bifidobacterium_animalis
27 Apr 2020 05:44:27: > Error 2:
27 Apr 2020 05:44:27: > fatal error while working on Bifidobacterium_animalis check logfile /primerdesign/speciesprimer_2020_04_27.log
”“”

**Comment by aiqubo** [comment]
work now, After I updated the blastdb use command as follow
""update_blastdb.pl --passive --decompress ref_prok_rep_genomes""
